name: Weekly updates
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#project-automation

on:
  workflow_dispatch:
    schedule:
      - cron: "1 0 * * 1" # just after midnight on Monday

jobs:
  make_post:
    name: Create post on Make site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish post
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const { main } = await import('${{ github.workspace}}/automations/js/src/last_week_tonight.mjs'
            await main(github, core)
